set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN Y14 [get_ports sys_clk]

set_property PACKAGE_PIN H1 [get_ports vout_clk]
set_property PACKAGE_PIN G3 [get_ports {vout_data[0]}]
set_property PACKAGE_PIN H3 [get_ports {vout_data[1]}]
set_property PACKAGE_PIN H4 [get_ports {vout_data[2]}]
set_property PACKAGE_PIN G7 [get_ports {vout_data[3]}]
set_property PACKAGE_PIN G8 [get_ports {vout_data[4]}]
set_property PACKAGE_PIN G1 [get_ports {vout_data[5]}]
set_property PACKAGE_PIN H5 [get_ports {vout_data[6]}]
set_property PACKAGE_PIN H6 [get_ports {vout_data[7]}]
set_property PACKAGE_PIN G4 [get_ports {vout_data[8]}]
set_property PACKAGE_PIN F4 [get_ports {vout_data[9]}]
set_property PACKAGE_PIN F5 [get_ports {vout_data[10]}]
set_property PACKAGE_PIN E5 [get_ports {vout_data[11]}]
set_property PACKAGE_PIN G6 [get_ports {vout_data[12]}]
set_property PACKAGE_PIN F6 [get_ports {vout_data[13]}]
set_property PACKAGE_PIN E7 [get_ports {vout_data[14]}]
set_property PACKAGE_PIN F7 [get_ports {vout_data[15]}]
set_property PACKAGE_PIN D3 [get_ports {vout_data[16]}]
set_property PACKAGE_PIN C3 [get_ports {vout_data[17]}]
set_property PACKAGE_PIN C4 [get_ports {vout_data[18]}]
set_property PACKAGE_PIN D5 [get_ports {vout_data[19]}]
set_property PACKAGE_PIN C5 [get_ports {vout_data[20]}]
set_property PACKAGE_PIN C6 [get_ports {vout_data[21]}]
set_property PACKAGE_PIN E8 [get_ports {vout_data[22]}]
set_property PACKAGE_PIN D8 [get_ports {vout_data[23]}]
set_property PACKAGE_PIN G2 [get_ports vout_de]
set_property PACKAGE_PIN E4 [get_ports vout_hs]
set_property PACKAGE_PIN L4 [get_ports hdmi_nreset]
set_property PACKAGE_PIN E3 [get_ports vout_vs]
set_property PACKAGE_PIN J8 [get_ports hdmi_scl]
set_property PACKAGE_PIN K8 [get_ports hdmi_sda]


set_property IOSTANDARD LVCMOS33 [get_ports vout_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {vout_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vout_de]
set_property IOSTANDARD LVCMOS33 [get_ports vout_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_nreset]
set_property IOSTANDARD LVCMOS33 [get_ports vout_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]

set_property IOB TRUE [get_ports {vout_data[*]}]
set_property IOB TRUE [get_ports vout_de]
set_property IOB TRUE [get_ports vout_hs]
set_property IOB TRUE [get_ports vout_vs]

set_property SLEW FAST [get_ports {vout_data[*]}]
set_property SLEW FAST [get_ports vout_de]
set_property SLEW FAST [get_ports vout_hs]
set_property SLEW FAST [get_ports vout_vs]
set_property SLEW FAST [get_ports vout_clk]


set_property PACKAGE_PIN AA16 [get_ports vin_clk]
set_property PACKAGE_PIN U17 [get_ports {vin_data[0]}]
set_property PACKAGE_PIN V16 [get_ports {vin_data[1]}]
set_property PACKAGE_PIN W16 [get_ports {vin_data[2]}]
set_property PACKAGE_PIN AA17 [get_ports {vin_data[3]}]
set_property PACKAGE_PIN Y19 [get_ports {vin_data[4]}]
set_property PACKAGE_PIN Y18 [get_ports {vin_data[5]}]
set_property PACKAGE_PIN AA15 [get_ports {vin_data[6]}]
set_property PACKAGE_PIN AA14 [get_ports {vin_data[7]}]
set_property PACKAGE_PIN AB16 [get_ports {vin_data[8]}]
set_property PACKAGE_PIN AB17 [get_ports {vin_data[9]}]
set_property PACKAGE_PIN AB19 [get_ports {vin_data[10]}]
set_property PACKAGE_PIN AB18 [get_ports {vin_data[11]}]
set_property PACKAGE_PIN Y15 [get_ports {vin_data[12]}]
set_property PACKAGE_PIN U16 [get_ports {vin_data[13]}]
set_property PACKAGE_PIN V14 [get_ports {vin_data[14]}]
set_property PACKAGE_PIN V13 [get_ports {vin_data[15]}]
set_property PACKAGE_PIN AB11 [get_ports {vin_data[16]}]
set_property PACKAGE_PIN AA11 [get_ports {vin_data[17]}]
set_property PACKAGE_PIN V11 [get_ports {vin_data[18]}]
set_property PACKAGE_PIN W11 [get_ports {vin_data[19]}]
set_property PACKAGE_PIN W12 [get_ports {vin_data[20]}]
set_property PACKAGE_PIN W13 [get_ports {vin_data[21]}]
set_property PACKAGE_PIN U12 [get_ports {vin_data[22]}]
set_property PACKAGE_PIN U11 [get_ports {vin_data[23]}]
set_property PACKAGE_PIN V19 [get_ports vin_de]
set_property PACKAGE_PIN U19 [get_ports vin_hs]
set_property PACKAGE_PIN P1 [get_ports hdmi_in_nreset]
set_property PACKAGE_PIN U18 [get_ports vin_vs]

set_property IOSTANDARD LVCMOS33 [get_ports vin_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {vin_data[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports vin_de]
set_property IOSTANDARD LVCMOS33 [get_ports vin_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vin_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_in_nreset]

set_property IOB TRUE [get_ports {vin_data[*]}]
set_property IOB TRUE [get_ports vin_de]
set_property IOB TRUE [get_ports vin_hs]
set_property IOB TRUE [get_ports vin_vs]

#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets vout_clk_OBUF]


set_property DRIVE 12 [get_ports {vout_data[*]}]
set_property DRIVE 16 [get_ports vout_clk]
set_property DRIVE 12 [get_ports vout_de]
set_property DRIVE 12 [get_ports vout_hs]

create_clock -period 6.734 -name vin_clk -waveform {0.000 3.367} [get_ports vin_clk]
set_input_delay -clock [get_clocks vin_clk] -min -add_delay 1.010 [get_ports {vin_data[*]}]
set_input_delay -clock [get_clocks vin_clk] -max -add_delay 3.500 [get_ports {vin_data[*]}]
set_input_delay -clock [get_clocks vin_clk] -min -add_delay 1.010 [get_ports vin_de]
set_input_delay -clock [get_clocks vin_clk] -max -add_delay 3.500 [get_ports vin_de]
set_input_delay -clock [get_clocks vin_clk] -min -add_delay 1.010 [get_ports vin_hs]
set_input_delay -clock [get_clocks vin_clk] -max -add_delay 3.500 [get_ports vin_hs]
set_input_delay -clock [get_clocks vin_clk] -min -add_delay 1.010 [get_ports vin_vs]
set_input_delay -clock [get_clocks vin_clk] -max -add_delay 3.500 [get_ports vin_vs]



create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list vout_clk_OBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {vin_data_IBUF[0]} {vin_data_IBUF[1]} {vin_data_IBUF[2]} {vin_data_IBUF[3]} {vin_data_IBUF[4]} {vin_data_IBUF[5]} {vin_data_IBUF[6]} {vin_data_IBUF[7]} {vin_data_IBUF[8]} {vin_data_IBUF[9]} {vin_data_IBUF[10]} {vin_data_IBUF[11]} {vin_data_IBUF[12]} {vin_data_IBUF[13]} {vin_data_IBUF[14]} {vin_data_IBUF[15]} {vin_data_IBUF[16]} {vin_data_IBUF[17]} {vin_data_IBUF[18]} {vin_data_IBUF[19]} {vin_data_IBUF[20]} {vin_data_IBUF[21]} {vin_data_IBUF[22]} {vin_data_IBUF[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list vin_de_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list vin_hs_IBUF]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list vin_vs_IBUF]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets vout_clk_OBUF_BUFG]
