#Clock signal
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN Y14 [get_ports sys_clk]
create_clock -period 20.000 -name sys_clk -waveform {0.000 10.000} [get_ports sys_clk]

set_property PACKAGE_PIN H1 [get_ports hdmi_clk]
set_property PACKAGE_PIN G3 [get_ports {hdmi_d[0]}]
set_property PACKAGE_PIN H3 [get_ports {hdmi_d[1]}]
set_property PACKAGE_PIN H4 [get_ports {hdmi_d[2]}]
set_property PACKAGE_PIN G7 [get_ports {hdmi_d[3]}]
set_property PACKAGE_PIN G8 [get_ports {hdmi_d[4]}]
set_property PACKAGE_PIN G1 [get_ports {hdmi_d[5]}]
set_property PACKAGE_PIN H5 [get_ports {hdmi_d[6]}]
set_property PACKAGE_PIN H6 [get_ports {hdmi_d[7]}]
set_property PACKAGE_PIN G4 [get_ports {hdmi_d[8]}]
set_property PACKAGE_PIN F4 [get_ports {hdmi_d[9]}]
set_property PACKAGE_PIN F5 [get_ports {hdmi_d[10]}]
set_property PACKAGE_PIN E5 [get_ports {hdmi_d[11]}]
set_property PACKAGE_PIN G6 [get_ports {hdmi_d[12]}]
set_property PACKAGE_PIN F6 [get_ports {hdmi_d[13]}]
set_property PACKAGE_PIN E7 [get_ports {hdmi_d[14]}]
set_property PACKAGE_PIN F7 [get_ports {hdmi_d[15]}]
set_property PACKAGE_PIN D3 [get_ports {hdmi_d[16]}]
set_property PACKAGE_PIN C3 [get_ports {hdmi_d[17]}]
set_property PACKAGE_PIN C4 [get_ports {hdmi_d[18]}]
set_property PACKAGE_PIN D5 [get_ports {hdmi_d[19]}]
set_property PACKAGE_PIN C5 [get_ports {hdmi_d[20]}]
set_property PACKAGE_PIN C6 [get_ports {hdmi_d[21]}]
set_property PACKAGE_PIN E8 [get_ports {hdmi_d[22]}]
set_property PACKAGE_PIN D8 [get_ports {hdmi_d[23]}]
set_property PACKAGE_PIN G2 [get_ports hdmi_de]
set_property PACKAGE_PIN E4 [get_ports hdmi_hs]
set_property PACKAGE_PIN L4 [get_ports hdmi_rst_n]
set_property PACKAGE_PIN E3 [get_ports hdmi_vs]
set_property PACKAGE_PIN J8 [get_ports hdmi_scl]
set_property PACKAGE_PIN K8 [get_ports hdmi_sda]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_scl]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_sda]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_d[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_de]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_vs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_hs]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_rst_n]

set_property SLEW FAST [get_ports {hdmi_d[*]}]
set_property DRIVE 8 [get_ports {hdmi_d[*]}]
set_property SLEW FAST [get_ports hdmi_clk]
set_property SLEW FAST [get_ports hdmi_de]
set_property SLEW FAST [get_ports hdmi_hs]
set_property SLEW FAST [get_ports hdmi_scl]
set_property SLEW FAST [get_ports hdmi_sda]
set_property SLEW FAST [get_ports hdmi_vs]