## This file is a general .xdc for the ALINX AX7015 board
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property PACKAGE_PIN Y14 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]


set_property PACKAGE_PIN AB12 [get_ports {btns_tri_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {btns_tri_i[0]}]

set_property PACKAGE_PIN A5 [get_ports {leds_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[0]}]

set_property PACKAGE_PIN A7 [get_ports {leds_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[1]}]

set_property PACKAGE_PIN A6 [get_ports {leds_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[2]}]

set_property PACKAGE_PIN B8 [get_ports {leds_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {leds_tri_o[3]}]

set_property PACKAGE_PIN H1 [get_ports hdmi_clk]
set_property PACKAGE_PIN G3 [get_ports {hdmi_d[0]}]
set_property PACKAGE_PIN H3 [get_ports {hdmi_d[1]}]
set_property PACKAGE_PIN H4 [get_ports {hdmi_d[2]}]
set_property PACKAGE_PIN G7 [get_ports {hdmi_d[3]}]
set_property PACKAGE_PIN G8 [get_ports {hdmi_d[4]}]
set_property PACKAGE_PIN G1 [get_ports {hdmi_d[5]}]
set_property PACKAGE_PIN H5 [get_ports {hdmi_d[6]}]
set_property PACKAGE_PIN H6 [get_ports {hdmi_d[7]}]
set_property PACKAGE_PIN G4 [get_ports {hdmi_d[8]}]
set_property PACKAGE_PIN F4 [get_ports {hdmi_d[9]}]
set_property PACKAGE_PIN F5 [get_ports {hdmi_d[10]}]
set_property PACKAGE_PIN E5 [get_ports {hdmi_d[11]}]
set_property PACKAGE_PIN G6 [get_ports {hdmi_d[12]}]
set_property PACKAGE_PIN F6 [get_ports {hdmi_d[13]}]
set_property PACKAGE_PIN E7 [get_ports {hdmi_d[14]}]
set_property PACKAGE_PIN F7 [get_ports {hdmi_d[15]}]
set_property PACKAGE_PIN D3 [get_ports {hdmi_d[16]}]
set_property PACKAGE_PIN C3 [get_ports {hdmi_d[17]}]
set_property PACKAGE_PIN C4 [get_ports {hdmi_d[18]}]
set_property PACKAGE_PIN D5 [get_ports {hdmi_d[19]}]
set_property PACKAGE_PIN C5 [get_ports {hdmi_d[20]}]
set_property PACKAGE_PIN C6 [get_ports {hdmi_d[21]}]
set_property PACKAGE_PIN E8 [get_ports {hdmi_d[22]}]
set_property PACKAGE_PIN D8 [get_ports {hdmi_d[23]}]
set_property PACKAGE_PIN G2 [get_ports hdmi_de]
set_property PACKAGE_PIN E4 [get_ports hdmi_hs]
set_property PACKAGE_PIN L4 [get_ports {hdmi_nreset_tri_o[0]}]
set_property PACKAGE_PIN E3 [get_ports hdmi_vs]
set_property PACKAGE_PIN J8 [get_ports hdmi_i2c_scl_io]
set_property PACKAGE_PIN K8 [get_ports hdmi_i2c_sda_io]

set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_sda_io]
set_property IOSTANDARD LVTTL [get_ports {hdmi_d[*]}]
set_property IOSTANDARD LVTTL [get_ports hdmi_clk]
set_property IOSTANDARD LVTTL [get_ports hdmi_de]
set_property IOSTANDARD LVTTL [get_ports hdmi_vs]
set_property IOSTANDARD LVTTL [get_ports hdmi_hs]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_nreset_tri_o[0]}]

set_property SLEW FAST [get_ports {hdmi_d[*]}]
set_property DRIVE 24 [get_ports {hdmi_d[*]}]
set_property DRIVE 24 [get_ports hdmi_clk]
set_property SLEW FAST [get_ports hdmi_clk]
set_property SLEW FAST [get_ports hdmi_de]
set_property SLEW FAST [get_ports hdmi_hs]
set_property SLEW FAST [get_ports hdmi_vs]
set_property IOB TRUE [get_ports {hdmi_d[*]}]
set_property IOB TRUE [get_ports hdmi_de]
set_property IOB TRUE [get_ports hdmi_hs]
set_property IOB TRUE [get_ports hdmi_vs]

set_property PACKAGE_PIN C8 [get_ports mdio_mdc]
set_property PACKAGE_PIN B6 [get_ports mdio_mdio_io]
set_property PACKAGE_PIN B7 [get_ports {phy_rst_n[0]}]
set_property PACKAGE_PIN B4 [get_ports rgmii_rxc]
set_property PACKAGE_PIN B3 [get_ports rgmii_rx_ctl]
set_property PACKAGE_PIN A2 [get_ports {rgmii_rd[0]}]
set_property PACKAGE_PIN A1 [get_ports {rgmii_rd[1]}]
set_property PACKAGE_PIN B2 [get_ports {rgmii_rd[2]}]
set_property PACKAGE_PIN B1 [get_ports {rgmii_rd[3]}]
set_property PACKAGE_PIN D1 [get_ports rgmii_txc]
set_property PACKAGE_PIN C1 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN F2 [get_ports {rgmii_td[0]}]
set_property PACKAGE_PIN F1 [get_ports {rgmii_td[1]}]
set_property PACKAGE_PIN E2 [get_ports {rgmii_td[2]}]
set_property PACKAGE_PIN D2 [get_ports {rgmii_td[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports mdio_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports {phy_rst_n[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_rd[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_txc]
set_property IOSTANDARD LVCMOS33 [get_ports rgmii_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports {rgmii_td[*]}]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets design_1_i/axi_ethernet_0_refclk/inst/clk_in1_system_axi_ethernet_0_refclk_0]

set_property DRIVE 24 [get_ports hdmi_de]
set_property DRIVE 24 [get_ports hdmi_hs]
set_property DRIVE 24 [get_ports hdmi_vs]
